project/cliente/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "cliente"

urlpatterns = [
    path("", views.crear, name="index"),
]

project/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("cliente", include("cliente.urls")),
    path("producto", include("producto.urls")),
]

project/core/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path("", views.home, name="index"),
    path("search/", views.buscar_cliente, name="search"),
]

project/producto/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "servicio"

urlpatterns = [
    path("", views.crear, name="index"),
]

project/cliente/models.py
from django.db import models

class Servicio(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField(blank=True)
    costo = models.DecimalField(max_digits=8, decimal_places=2)
    
    def __str__(self):
        return self.nombre

class Cliente(models.Model):
    nombre = models.CharField(max_length=100)
    telefono = models.CharField(max_length=15)
    email = models.EmailField()
    direccion = models.TextField(blank=True)
    
    def __str__(self):
        return self.nombre

class Reparacion(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    servicio = models.ForeignKey(Servicio, on_delete=models.CASCADE)
    fecha_reparacion = models.DateField()
    descripcion = models.TextField(blank=True)
    
    def __str__(self):
        return f"{self.servicio.nombre} para {self.cliente.nombre}"

project/core/models.py
from django.db import models
from cliente.models import Reparacion
# Create your models here.

project/producto/models.py
from django.db import models
from cliente.models import Servicio

project/cliente/forms.py
from django import forms
from . import models

class ClienteForm(forms.ModelForm):
    class Meta:
        model = models.Cliente
        fields="__all__"

project/core/forms.py
from django import forms
from . import models
from cliente.models import Reparacion,Cliente

class ReparacionForm(forms.ModelForm):
    class Meta:
        model = models.Reparacion
        fields="__all__"

class BusquedaForm(forms.Form):
    nombre = forms.CharField(max_length=100, label='Buscar')

project/producto/forms.py
from django import forms
from . import models
from cliente.models import Servicio

class ServicioForm(forms.ModelForm):
    class Meta:
        model = models.Servicio
        fields="__all__"

project/cliente/views.py
from django.shortcuts import render, redirect
from .forms import ClienteForm
from .models import Cliente

def crear(request):
    if request.method == "POST":
        form = ClienteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("home:index")
    else:
        form = ClienteForm()
    return render(request, "cliente/index.html", {"form": form})

project/core/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from .forms import ReparacionForm,BusquedaForm
from cliente.models import Cliente, Reparacion
from django import forms

def home(request):
    if request.method == "POST":
        form = ReparacionForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("home:index")
    else:
        form = ReparacionForm()
    return render(request, "core/index.html", {"form": form})

def buscar_cliente(request):
    form = BusquedaForm(request.GET)
    resultados = None
    
    if request.method == 'GET' and 'nombre' in request.GET:
        form = BusquedaForm(request.GET)
        if form.is_valid():
            nombre = form.cleaned_data['nombre']
            resultados = Cliente.objects.filter(nombre__icontains=nombre)
    
    return render(request, 'core/buscar.html', {'form': form, 'resultados': resultados})

project/producto/views.py
from django.shortcuts import render, redirect
from .forms import ServicioForm
from cliente.models import Servicio

def crear(request):
    if request.method == "POST":
        form = ServicioForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("home:index")
    else:
        form = ServicioForm()
    return render(request, "producto/index.html", {"form": form})

project/cliente/templates/cliente/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    CLIENTE
</body>
</html>

project/core/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>CT Reparaciones</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'core/assets/favicon.ico' %}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'core/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigationbar-->

{% include 'core/navbar.html' %}

        <!-- Masthead-->
        <header class="masthead">
            <div class="container position-relative">
                
                <h1>
                {% block cont_title %}
                {% endblock cont_title %}
                </h1>

                {% block content %}
                {% endblock content %}

        <!-- Footer-->

        {% include 'core/footer.html' %}

        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'core/js/scripts.js' %}"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

project/core/templates/core/buscar.html
{% extends 'core/index.html' %}

{% block cont_title %}   
{% endblock cont_title %}

{% block content %}

    <div class="row justify-content-center">
        <div class="col-xl-6">
            <div class="text-center text-white">
                <!-- Page heading-->
                <h1 class="mb-5">Buscar cliente</h1>
                <form method="GET">
                    {{ form.as_p }}
                    <button type="submit">Buscar</button>
                </form>
                
                {% if resultados %}
                    <ul>
                        {% for producto in resultados %}
                            <h2>{{ producto.nombre }} y su correo es {{ producto.email }}</h2>
                        {% endfor %}
                    </ul>
                {% else %}
                    <h2>No se encontraron resultados.</h2>
                {% endif %}            
            </form>
        </div>
    </div>

{% endblock content %}

project/core/templates/core/footer.html
      <!-- Footer-->
      
<footer class="footer bg-light">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                <p class="text-muted small mb-4 mb-lg-0">&copy; Website de la 3ra Entrega de CoderHouse. Carlos Tavares-477990.</p>
            </div>
            <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                <ul class="list-inline mb-0">
                    <li class="list-inline-item me-4">
                        <a href="https://www.facebook.com/c.tavaresalm"><i class="bi-facebook fs-3"></i></a>
                    </li>
                    <li class="list-inline-item me-4">
                        <a href="https://www.twitter.com/artgamescollect"><i class="bi-twitter fs-3"></i></a>
                    </li>
                    <li class="list-inline-item">
                        <a href="https://www.instagram.com/carlos.tavaresa"><i class="bi-instagram fs-3"></i></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

project/core/templates/core/icon.html
<!-- Icons Grid-->
<div class="col-lg-4">
    <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
        <div class="features-icons-icon d-flex"><i class="bi-window m-auto text-primary"></i></div>
        <h3>{{title}}</h3>
        <p class="lead mb-0">{{body}}</p>
    </div>
</div>

project/core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}

{% block cont_title %}
{% endblock cont_title %}

{% block content %}
<!-- Icons Grid-->
<section class="features-icons bg-light text-center">
<div class="container">
<div class="row">
    {% include 'core/icon.html' with title="Primer paso" body="Ir a registrar al nuevo cliente (saltar este paso si ya existe)" %}
    {% include 'core/icon.html' with title="Segundo paso" body="Ir a 'Servicio' para registrar un servicio' (saltar este paso si ya existe)" %}
    {% include 'core/icon.html' with title="tercera" body="Ir a 'Inicio' para generar la factura al cliente" %}
</div>  
</section> 

<div class="row justify-content-center">
    <div class="col-xl-6">
        <div class="text-center text-white">
            <!-- Page heading-->
            <h1 class="mb-5">Registro de factura</h1>
            <form method="post">
                {% csrf_token %}
            {% csrf_token %}
            {{ form.as_p }}
            <button type="Submit" class="btn btn-primary">Guardar</button>
        </form>
    </div>
</div>

{% endblock content %}

project/core/templates/core/navbar.html
        <!-- Navigationbar-->

<nav class="navbar navbar-light bg-light static-top">
    <div class="container">
        <a class="btn btn-primary" href="{% url 'home:index' %}">Inicio</a>
        <a class="btn btn-primary" href="{% url 'cliente:index' %}">Cliente</a>
        <a class="btn btn-primary" href="{% url 'servicio:index' %}">Servicio</a>
        <a class="btn btn-primary" href="{% url 'home:search' %}">Buscar cliente</a>
    </div>
</nav>  

project/core/templates/core/result.html
{% extends 'core/base.html' %}

{% block cont_title %}   
{% endblock cont_title %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-xl-6">
        <div class="text-center text-white">
            <!-- Page heading-->
            <h1 class="mb-5">Registro de cliente</h1>
            <form method="post">
                {% csrf_token %}
            {% csrf_token %}
            {{ form.as_p }}
            <button type="Submit" class="btn btn-primary">Guardar</button>
        </form>
    </div>
</div>
{% endblock content %}

project/producto/templates/producto/index.html
{% extends 'core/base.html' %}

{% block cont_title %}   
{% endblock cont_title %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-xl-6">
        <div class="text-center text-white">
            <!-- Page heading-->
            <h1 class="mb-5">Registro de servicio</h1>
            <form method="post">
                {% csrf_token %}
            {% csrf_token %}
            {{ form.as_p }}
            <button type="Submit" class="btn btn-primary">Guardar</button>
        </form>
    </div>
</div>
{% endblock content %}